### PR TITLE
Telegram Implementation

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by Sano328** [comment]
Bad evaluation

**Comment by timyates** [comment]
Anything we can do about the 46 code smells?

**Comment by sdelamo** [comment]
> Anything we can do about the 46 code smells?

I don't really know how to solve those.

**Review by timyates — APPROVED** [review]
Fixed a couple of the smells, and added a duplication ignore rule for Sonar on the API Serde DTOs

Still a few left, can you check they are ok?

**Pull request merged**
